### PR TITLE
More changes to the dipy xvfb bots.

### PR DESCRIPTION
**Pull request by arokem**

### CODE REVIEW

**Comment by matthew-brett** [comment]
Ariel - I recommend testing by logging into the buildbot machine, editing
and running `buildbot reconfigure` - is that what you are doing?​

**Comment by Garyfallidis** [comment]
We want to simply enable some env variables. What is the best way to do so?

**Comment by matthew-brett** [comment]
Doesn't look obviously wrong what you did, but quickest is to try stuff and see what works.  Buildbot can be fiddly.

**Comment by arokem** [comment]
Is that documented somewhere (how to log into these things, what to do once
you have logged in, etc.)?

I am sorry to say that I have no idea how to even get started here.
Shooting in the dark, as it were.

**Comment by matthew-brett** [comment]
Just:

```
ssh buildbot@nipy.bic.berkeley.edu
cd nibotmi
vim master.cfg
buildbot reconfig
```

**Comment by arokem** [comment]
OK - I am trying to do this, but it seems that:

1. The master.cfg on that machine has diverged from the master branch on
the github repository. There are both uncommited changes to this file on
nipy.bic.berkeley.edu, as well as changes that haven't been pulled in from
github.
2. Trying to resolve this through git doesn't really work for me. Doing a
`git pull origin master`, I get `Permission denied (publickey).` from git.

**Comment by arokem** [comment]
For now, I have resolved it by committing all the local changes, creating a
new remote with the nipy/nibotmi https address and pulling from there.

**Pull request merged**
